name: Continuous Integration Benchmarks

on:
  push:
    branches: [ master ]
    paths:
      - '!**'
      - 'thp-benchmark.sh'
      - 'thp-always.service.d/thp-always.sh'
      - .github/workflows/ci.yml
  pull_request:
    branches: [ master ]
    paths:
      - '!**'
      - 'thp-benchmark.sh'
      - 'thp-always.service.d/thp-always.sh'
      - .github/workflows/ci.yml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6

    - name: Install Ubuntu packages
      run: |
        sudo apt-get update --yes
        sudo apt-get install --yes coreutils sed stress-ng icdiff

    - name: Disable autogroup
      run: sudo bash -c 'echo 0 > /proc/sys/kernel/sched_autogroup_enabled'

    - name: Run THP benchmark
      run: ./"thp-benchmark.sh"
